name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Build
        run: go build -v ./...
        working-directory: ./train1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Run tests
        run: go test -v ./...
        working-directory: ./train1

  test-race:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Run race tests
        run: go test -race -v ./...
        working-directory: ./train1

  lint:
    runs-on: ubuntu-latest
    needs: [test, test-race]
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./train1
