name: Go CI

on:
  push:
    branches: ["new_workflow"]
  pull_request:
    branches: ["new_workflow"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Build
        run: go build -v ./...
        working-directory: ./train1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: train1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Run tests
        run: go test -v ./...
        working-directory: ./train1
